version: '2'
services:

  nginx:
    image: opentracing/nginx-opentracing
    networks:
      nexmotracing:
        aliases:
          - nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/jaeger-config.json:/etc/jaeger-config.json
    expose:
      - "8080"
    ports:
      - "8080:8080"
    depends_on:
      - auth-service
      - quota-service
      - messages-api-service

  auth-service:
    image: peterjurkovic/opentracing-auth:latest
    networks:
      nexmotracing:
        aliases:
          - auth-service
    expose:
      - "3030"
    ports:
      - "3030:3030"
    environment:
      - AUTH_SERVER_PORT=3030

  quota-service:
    image: peterjurkovic/opentracing-quota:latest
    networks:
      nexmotracing:
        aliases:
          - quota-service
    expose:
      - "6060"
    ports:
      - "6060:6060"
    environment:
      - QUOTA_HTTP_COLLECTOR_URL=http://jaeger:14268/api/traces

  messages-api-service:
    image: peterjurkovic/opentracing-messages-api:latest
    networks:
      nexmotracing:
        aliases:
          - messages-api-service
    expose:
      - "7070"
    ports:
      - "7070:7070"
    environment:
      - HTTP_COLLECTOR_URL=http://jaeger:14268/api/traces
      - AUTH_HOST=nginx
      - QUOTA_HOST=nginx
      - KAFKA_HOST=kafka:9092
    depends_on:
      - auth-service
      - quota-service
      - kafka

  messages-backend-service:
    image: peterjurkovic/opentracing-messages-backend:latest
    networks:
      nexmotracing:
        aliases:
          - messages-backend-service
    expose:
      - "8080"
    ports:
      - "7080:7080"
    environment:
      - HTTP_COLLECTOR_URL=http://jaeger:14268/api/traces
      - KAFKA_HOST=kafka:9092
    depends_on:
      - kafka

  jaeger:
    image: jaegertracing/all-in-one
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    networks:
      nexmotracing:
        aliases:
          - jaeger
    expose:
      - "5775"
      - "6831"
      - "6832"
      - "5778"
      - "9411"
      - "14268"
      - "16686"
    ports:
      - "5775:5775"
      - "6831:6831"
      - "6832:6832"
      - "5778:5778"
      - "9411:9411"
      - "14268:14268"
      - "16686:16686"

  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      nexmotracing:
        aliases:
          - zookeeper
  
  kafka:
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    networks:
      nexmotracing:
        aliases:
          - kafka
    depends_on:
        - zookeeper
    
networks:
  nexmotracing: {}