version: '2'
services:

  nginx:
    image: opentracing/nginx-opentracing
    networks:
      nexmotracing:
        aliases:
          - nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/jaeger-config.json:/etc/jaeger-config.json
    expose:
      - "8080"
    ports:
      - "8080:8080"
    depends_on:
      - auth-service
      - quota-service
      - chatapp-service

  auth-service:
    build:
      context: ./auth/
      dockerfile: ./Dockerfile
    networks:
      nexmotracing:
        aliases:
          - auth-service
    expose:
      - "3030"
    ports:
      - "3030:3030"
    environment:
      - AUTH_SERVER_PORT=3030

  quota-service:
    build:
      context: ./quota/
      dockerfile: ./Dockerfile
    networks:
      nexmotracing:
        aliases:
          - quota-service
    expose:
      - "6060"
    ports:
      - "6060:6060"
    environment:
      - QUOTA_HTTP_COLLECTOR_URL=http://jaeger:14268/api/traces

  chatapp-service:
    build:
      context: ./chatapp/
      dockerfile: ./Dockerfile
    networks:
      nexmotracing:
        aliases:
          - chatapp-service
    expose:
      - "7070"
    ports:
      - "7070:7070"
    environment:
      - CHATAPP_HTTP_COLLECTOR_URL=http://jaeger:14268/api/traces
      - AUTH_HOST=nginx
      - QUOTA_HOST=nginx
    depends_on:
      - auth-service
      - quota-service

  jaeger:
    image: jaegertracing/all-in-one
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    networks:
      nexmotracing:
        aliases:
          - jaeger
    expose:
      - "5775"
      - "6831"
      - "6832"
      - "5778"
      - "9411"
      - "14268"
      - "16686"
    ports:
      - "5775:5775"
      - "6831:6831"
      - "6832:6832"
      - "5778:5778"
      - "9411:9411"
      - "14268:14268"
      - "16686:16686"
      
      
 
networks:
  nexmotracing: {}